name:  PostgreSQL
description: |
   PostgreSQL — an object-relational database (ORDBMS)
version:  1.0.0
category:  WEB
maintainer:  variable
license:  Apache 2
projectURL: https://github.com/Variable1/shopApp
