version: '2'
services:
  scada-db:
    image: 10.168.4.80/scada1.0/scada-db:5.5.59
    environment:
      MYSQL_ROOT_PASSWORD: root123
    stdin_open: true
    volumes:
    - /usr/data/scada-one/:/usr/local/mysql/data/
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: node=node3
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  scada:
    image: 10.168.4.80/scada1.0/scada:7
    links:
    - scada-db:mydb
    ports:
    - 9695:8080/tcp
