version: '2'
.catalog:
  name:  scada-one
  version:  1.0.0
  description:  nginx image
  uuid: scada-one-1
  minimum_rancher_version: V1.0.0
  questions: #
services:
  config-service:
    retain_ip: true
    scale: 1
    start_on_create: true
  iot-open:
    scale: 1
    start_on_create: true
  basics-service:
    scale: 1
    start_on_create: true
  user-service:
    scale: 1
    start_on_create: true
  iot-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: registry-service0
        source_port: 8761
        target_port: 8761
      - priority: 2
        protocol: http
        service: gateway-service
        source_port: 4000
        target_port: 4000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  basesdb:
    scale: 1
    start_on_create: true
  outprotocol-gateway:
    scale: 1
    start_on_create: true
  in-modbus:
    scale: 1
    start_on_create: true
  out-rabbitmq:
    scale: 1
    start_on_create: true
  inprotocol-gateway:
    scale: 1
    start_on_create: true
  gateway-service:
    scale: 1
    start_on_create: true
  registry-service1:
    scale: 1
    start_on_create: true
  registry-service2:
    scale: 1
    start_on_create: true
  registry-service0:
    scale: 1
    start_on_create: true
